### ISSUE TITLE
Unable to use protobuf-c generated code.

### ISSUE THREAD

**Issue by BharathZoho** [RedisLabs/RedisModulesSDK#20]
Hi, 
    I tried writing a redis module which used protobuf. I used the following protobuf (for C) 
https://github.com/protobuf-c/protobuf-c. I am able to compile and link the module but when i load the module while starting the redis-server, i get the following message,

# Module /Users/bharath-2336/redismodules/module.so failed to load: dlopen(/Users/bharath-2336/redismodules/module.so, 6): Symbol not found: _protobuf_c_message_free_unpacked
  Referenced from: /Users/bharath-2336/redismodules/module.so
  Expected in: flat namespace
 in /Users/bharath-2336/redismodules/module.so

**Comment by dvirsky** [comment]
Hi.
This is not a modules SDK issue. You need to add the linking to protobuf in your Makefile. I'm not 100% sure what the correct flags are, but you can see the instructions here: https://github.com/protobuf-c/protobuf-c#synopsis

I'm closing this as this is not a RedisModulesSDK issue.
