### ISSUE TITLE
Current codebase example does not build

### ISSUE THREAD

**Issue by atlantageek** [RedisLabs/RedisModulesSDK#24]
Im getting the following 2 error when I try to build
module.c:140:73: error: macro "RMUtil_RegisterWriteCmd" passed 4 arguments, but takes just 3
   RMUtil_RegisterWriteCmd(ctx, "example.hgetset", HGetSetCommand, "fast");

module.c:68:28: error: macro "RMUTIL_ASSERT_NOERROR" requires 2 arguments, but only 1 given
   RMUTIL_ASSERT_NOERROR(rep);

**Comment by mnunberg** [comment]
Fixed in https://github.com/RedisLabs/RedisModulesSDK/commit/e756dd897fd08ac7eb8f3eb611c2cd4b591183c3
