### ISSUE TITLE
[quesiton]: Periodic Timer

### ISSUE THREAD

**Issue by detailyang** [RedisLabs/RedisModulesSDK#28]
Hello. Now I'm using the RMUtil_NewPeriodicTimer API to support periodic timer as the following:
```c
void timerCb(RedisModuleCtx *ctx, void *p) {
  int *x = p;
  (*x)++;
}

int testPeriodic() {
  int x = 0;
  struct RMUtilTimer *tm =
      RMUtil_NewPeriodicTimer(timerCb, &x, (struct timespec){.tv_sec = 0, .tv_nsec = 10000000});

  sleep(1);

  ASSERT_EQUAL(0, RMUtilTimer_Stop(tm));
  ASSERT(x > 0);
  ASSERT(x <= 100);
  RMUtilTimer_Free(tm);
  return 0;
}
```

However the ctx is NULL. Well more detail is `RedisModule_GetThreadSafeContext` is NULL , So the timer callback's ctx argument is NULL.

Any question? my redis version is 4.0-rc3

**Comment by detailyang** [comment]
Well. After install latest redis branch ctx is okay. However, in my sense i will create a timer then periodic update the specified key as the following:

```bash
void timerCb(RedisModuleCtx *ctx, void *p) {
    RedisModuleCallReply *reply;
    reply = RedisModule_Call(ctx,"SET","a", "1");
    if (reply != NULL) {
        RedisModule_FreeCallReply(reply);
    }
}

int testPeriodic() {
  int x = 0;
  struct RMUtilTimer *tm =
      RMUtil_NewPeriodicTimer(timerCb, &x, (struct timespec){.tv_sec = 0, .tv_nsec = 10000000});

  sleep(1);

  ASSERT_EQUAL(0, RMUtilTimer_Stop(tm));
  ASSERT(x > 0);
  ASSERT(x <= 100);
  RMUtilTimer_Free(tm);
  return 0;
}
```

It looks like failed, because cannot get the `a` value by redis-cli get a :(

**Comment by dvirsky** [comment]
So regarding the NULL ctx - you got it right, you need the latest version of redis.

Regarding the call - first of all, you need to lock the context manually for this to be safe. 

Wrap any access to redis with
```c
    RedisModule_ThreadSafeContextLock(ctx);
     /* .... your code here ... */
   RedisModule_ThreadSafeContextUnlock(ctx);
 ```
There is no reason for this not to work, I'm using the same pattern myself - but try to see what the reply is and print it.

**Comment by dvirsky** [comment]
oh, another thing to notice - this will certainly not work in the context of the unit test, your code must be running inside a module, yeah? :)

**Comment by detailyang** [comment]
Yep, it's running inside module. `RedisModule_ThreadSafeContextLock` context lock is good :). But `RedisModule_Call(ctx,"SET","a", "1");` it doest work :(

**Comment by dvirsky** [comment]
Let me try it. I had no problem running module commands from this utility.

**Comment by detailyang** [comment]
@dvirsky Thanks. It will be awesome if it's okay . I am eager to set specified key new value in the timer.

**Comment by dvirsky** [comment]
@detailyang the problem was in the way you invoke RedisModule_Call, the first argument after the command is a format specifier. In your case it should have been:

```c
  RedisModuleCallReply *r = RedisModule_Call(ctx, "SET", "cc", "a", "1");
```

See here: https://github.com/antirez/redis/blob/unstable/src/modules/INTRO.md#calling-redis-commands

**Comment by detailyang** [comment]
@dvirsky Sorry for the stupid error. I check again and now it's okay. Many Thanks !

**Comment by dvirsky** [comment]
@detailyang no problem, I hope you like it, I only wrote this utility yesterday! BTW What module are you trying to write?

**Comment by detailyang** [comment]
Well. I start write two redis modules today. One is `getex` module (which is get + ttl) (My scene is sensitive for the performance so I dont want to talk to redis twice). Another is ssl ticket rotate module, I will rotate the ssl ticket upon your `RMUtil_NewPeriodicTimer ` API in the redis master then syncing the ssl ticket to many redis slave.
