### ISSUE TITLE
failed to load: ./module.so: undefined symbol: RMUtil_AssertReplyEquals

### ISSUE THREAD

**Issue by anandanand84** [RedisLabs/RedisModulesSDK#31]
Could not load the built module, error Module ./module.so failed to load: ./module.so: undefined symbol: RMUtil_AssertReplyEquals.

**Steps to reproduce:**

Navigate to http://labs.play-with-docker.com/

```
docker run -it redis /bin/bash
apt-get update && apt-get install -y git build-essential
git clone https://github.com/RedisLabs/RedisModulesSDK.git
cd RedisModulesSDK/
make
redis-server --loadmodule ./module.so
```

**Comment by mnunberg** [comment]
Should be in order now. Try it.
