### ISSUE TITLE
What's the meaning of param 'fmt' in RM_CALL?

### ISSUE THREAD

**Issue by Sidfate** [RedisLabs/RedisModulesSDK#35]
In `Function.md`, i get the RM_Call definition, but be confused at param 'fmt'.

```c
RedisModuleCallReply *RM_Call(RedisModuleCtx *ctx, const char *cmdname, const char *fmt, ...);
```
and in `module.c`, 

```
RedisModule_Call(ctx, "HGET", "ss", argv[1], argv[2])
```

so, what do the param 'fmt' mean?how can i set the correct value in my own command?

**Comment by itamarhaber** [comment]
Hello @Sidfate 

These files are actually outdated copies of the docs at: https://redis.io/documentation#redis-modules-api

That said, for some reason, that part of the documentation is indeed missing for some reason. Please refer to https://github.com/antirez/redis/pull/5448 for more information.

**Comment by Sidfate** [comment]
@itamarhaber thx.
