### ISSUE TITLE
Native types in Redis modules

### ISSUE THREAD

**Issue by merl-dev** [RedisLabs/RedisModulesSDK#4]
I would strongly recommend making this section of anitrez's modules part of the SDK: https://github.com/antirez/redis/blob/unstable/src/modules/TYPES.md

**Comment by dvirsky** [comment]
yeah, you are right, we haven't updated the SDK since it was added. I'll do it soon unless you want to make a PR :)

**Comment by merl-dev** [comment]
No problem, I'll PR TYPES.md by tomorrow morning.

**Comment by merl-dev** [comment]
done!

**Comment by merl-dev** [comment]
see #5
