### ISSUE TITLE
RedisModuleString objects CANNOT be used as formatting arguments?

### ISSUE THREAD

**Issue by daTokenizer** [RedisLabs/RedisModulesSDK#7]
@dvirsky, Is there a concrete reason for that? 
This is a pretty useful thing to have, if it is matter of developing it just say so and i'll create a PR for that.

**Comment by dvirsky** [comment]
You are right, it will be useful. 

Basically we just pass the arguments as is to sds' formatting function, which doesn't recognize redis strings obviously. 

If you want to try and solve this, I'd look in the direction of extending printf. Although we don't use printf directly, it might work. See http://www.gnu.org/software/libc/manual/html_node/Customizing-Printf.html

**Comment by dvirsky** [comment]
And of course if you implement it I'd gladly merge a PR!

**Comment by daTokenizer** [comment]
so as it turns out, it is possible with a relatively simple process.

**Comment by allanlw** [comment]
I know this bug is closed, but to avoid [the DenverCoder9 problem](https://xkcd.com/979/), I'll just note that one way to do this easily is to use `RedisModule_StringPtrLen(s, NULL)` which will return a `const char *` that points to the contents of the RedisModuleString in question.

**Comment by daTokenizer** [comment]
yep, that the solution I reverted to as well back in the time..
