### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by daTokenizer** [RedisLabs/RedisModulesSDK#8]
make fails on both new code and example code.

this is the output:

```
RedisModulesSDK/example$ make all
ld -o module.so module.o -shared -Bsymbolic  -L../rmutil -lrmutil -lc 
ld: cannot find -lrmutil
Makefile:27: recipe for target 'module.so' failed
make: *** [module.so] Error 1
```

**Comment by dvirsky** [comment]
You should build `rmutil` first. We need to make a global makefile that builds both, but right now as mentioned in the README, you should build them in order:

> Build librmutil: cd rmutil && make
> Build the example module: cd example && make

**Comment by daTokenizer** [comment]
OK, that solved it :smile: (even though the make test_* still fails) for the love of me i cant figure out how come the compilation process fails in my module, since all the errors seem to originate in the rmutils lib (see a [log.txt](https://github.com/RedisLabs/RedisModulesSDK/files/395340/log.txt))
As far as I could tell there is some sort of problem with the expanded macro code, but with little familiarity 
with rmutils I was hoping to get a lead from you.


BTW the entire project is [here](https://github.com/TamarLabs/ReDehy)



cheers
adam

**Comment by dvirsky** [comment]
can you share your environment details?  os/compiler etc?

**Comment by daTokenizer** [comment]
$ uname -a
Linux habanero 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by daTokenizer** [comment]
🐛 bump
